### PR TITLE
Code simplification & generalization

### PR DESCRIPTION
**Pull request by valcarcexyz**
Hi there!
I added generalization to sudokus of size n on every function except the one that checks the sudokus.

I also simplified the code on the problem statement a lot: I removed a bunch of for loops that could be executed in one line, so it's easier to read. 

Once the problem is solved, I also changed how the sudoku solution is returned, for understanding I'll show you an example: 
Imagine you have a sudoku n = 1 with the following solution:

| 1 | 2 |
| ---|---|
| 2 | 1 |

The solution the software will return is 2 matrix, the first one containing whether the 1 is in the cell or not and the second one for the same with the second digit, so we have:
+ For "1":
equation

+ For "2":
equation

So the solution to the sudoku will be given by:
equation

### CODE REVIEW

**Comment by scheinerman** [comment]
I'll take a look once I figure out how to test your modifications before approving the PR. (I'm really confused about how Git works.) 

I don't see a change to `test/runtests.jl`. Perhaps you can expand the testing?

**Comment by valcarcexyz** [comment]
I have changed `test/runtests.jl` to run on other sudokus and added the generalization to `sudoku_check`. 
image

**Comment by scheinerman** [comment]
Hi Diego @valcarce01  : I was able to try this out and it seems to be working fine. I have a few more questions: 

- Can you add an `n=4` test? 
- Will `sudoku_print` work with `n=4` or higher? 
- In your email you mention an issue with "check". Does `sudoku_check` not work for `n=4`?
- In your email you said you changed the way the solution is presented, but it looks the same as before. That's fine. I'm not sure that an output of the solution as a linear combination of permutation matrices is reader friendly!

**Comment by scheinerman** [comment]
I think this is great! I plan to (1) merge, (2) update the `README` and version number, and (3) release the new version.

**Pull request merged**
